# Generated by Django 5.0.3 on 2025-05-29 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the blog post.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique slug for the URL (e.g., 'my-awesome-post').",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The main content of the blog post. Can contain HTML or Markdown."
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the post was created.",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time the post was last updated.",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Publish")],
                        default=0,
                        help_text="The publication status of the post (Draft or Publish).",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The author of this blog post.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-created_on"],
            },
        ),
    ]
