# Generated by Django 5.0.3 on 2025-05-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Publish"), (2, "Spotlight")],
                default=0,
                help_text="The publication status of the post (Draft or Publish).",
            ),
        ),
    ]
