# Generated by Django 5.0.3 on 2025-07-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Publish"), (2, "Listed"), (3, "Spotlight")],
                default=0,
                help_text="The publication status of the post (Draft or Publish).",
            ),
        ),
    ]
