# Generated by Django 5.0.3 on 2025-05-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The actual URL to which the link points (e.g., https://www.example.com).",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        help_text="The text that will be displayed for the link (e.g., 'Visit Example Website').",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="An optional, brief description of what the link is about.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this link was added.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this link was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link",
                "verbose_name_plural": "Links",
                "ordering": ["link_text"],
            },
        ),
    ]
