# Generated by Django 5.0.3 on 2025-07-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="category",
            field=models.IntegerField(
                choices=[(0, "ATProto"), (1, "Fediverse"), (2, "Open Web")],
                default=0,
                help_text="The category of the link (e.g., ATProto, Fediverse, Open Web).",
            ),
        ),
    ]
