# Generated by Django 5.0.3 on 2025-03-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("website", models.URLField(blank=True, null=True)),
                ("mastodon", models.CharField(blank=True, max_length=50, null=True)),
                ("bluesky", models.CharField(blank=True, max_length=50, null=True)),
                ("instagram", models.CharField(blank=True, max_length=50, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
