# Generated by Django 5.0.3 on 2025-03-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="slug",
            field=models.SlugField(blank=True, max_length=80, unique=True),
        ),
    ]
